scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: range
      type: laser_filters/LaserScanRangeFilter
      params:
        lower_threshold: 0.
        upper_threshold: 1.
        lower_replacement_value: .inf
        upper_replacement_value: .inf
        
    filter2:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -0.75
        upper_angle: 0.75
     
